name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        run: |
         sudo apt update
         sudo apt install build-essential
         sudo apt install *mingw-w64*
         sudo apt install mingw-w64 m4
         wget https://ftp.gnu.org/gnu/gcc/gcc-4.6.4/gcc-4.6.4.tar.gz
         wget https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2
         wget https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.gz
         wget https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz
         tar -xf gcc-4.6.4.tar.gz
         cd gcc-4.6.4
         tar -xf ../gmp-6.2.1.tar.bz2
         tar -xf ../mpfr-4.2.0.tar.gz
         tar -xf ../mpc-1.3.1.tar.gz
         mv gmp-6.2.1 gmp
         mv mpfr-4.2.0 mpfr
         mv mpc-1.3.1 mpc
         mkdir build
         cd build
         unset LIBRARY_PATH CPATH C_INCLUDE_PATH PKG_CONFIG_PATH CPLUS_INCLUDE_PATH INCLUDE
         ./../configure --prefix=/home/runner/work/gcc-build/gcc-build/install --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --enable-languages=c,c++ --disable-multilib --disable-bootstrap --disable-nls
         make
         make install
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/install
          retention -days: 3
