name: build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: artifact output
        continue-on-error: true
        run: |
          git config --global core.autocrlf false
          git clone https://github.com/llvm/llvm-project.git
          git checkout llvmorg-17.0.6
          cd llvm-project
          mkdir build
          cd build
          $Env:CC = "cl"
          $Env:CXX = "cl"
          cmake -GNinja -DLLVM_ENABLE_PROJECTS=clang ..\llvm
          ninja clang
      - name: artifact upload
        continue-on-error: true
        uses: actions/upload-artifact@v3.0.0
        with:
          name: llvm-clang
          path: D:\a\gcc-build\gcc-build\llvm-project\build
          retention -days: 3
