name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        run: |
         sudo apt update
         sudo apt install build-essential
         sudo apt install *mingw-w64*
         sudo apt install mingw-w64 m4
         wget https://ftp.gnu.org/gnu/gcc/gcc-6.2.0/gcc-6.2.0.tar.gz
         wget https://ftp.gnu.org/gnu/gmp/gmp-6.1.0.tar.bz2
         wget https://ftp.gnu.org/gnu/mpfr/mpfr-3.1.4.tar.gz
         wget https://ftp.gnu.org/gnu/mpc/mpc-1.0.3.tar.gz
         tar -xf gcc-6.2.0.tar.gz
         cd gcc-6.2.0
         tar -xf ../gmp-6.1.0.tar.bz2
         tar -xf ../mpfr-3.1.4.tar.gz
         tar -xf ../mpc-1.0.3.tar.gz
         mv gmp-6.1.0 gmp
         mv mpfr-3.1.4 mpfr
         mv mpc-1.0.3 mpc
         mkdir build
         cd build
         unset LIBRARY_PATH CPATH C_INCLUDE_PATH PKG_CONFIG_PATH CPLUS_INCLUDE_PATH INCLUDE
         sudo ./../configure CC=/bin/g++-x86_64-w64-mingw32-win32 --prefix=/home/runner/work/gcc-build/gcc-build/install --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --enable-languages=c,c++ --disable-multilib --disable-bootstrap --disable-nls
         sudo make
         sudo make install
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/install
          retention -days: 3
