name: build
on: [push]
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        continue-on-error: true
        run: |
         sudo apt update
         sudo apt install build-essential
         sudo apt install mingw-w64 m4
         wget https://ftp.gnu.org/gnu/gcc/gcc-3.4.6/gcc-core-3.4.6.tar.gz
         tar -xf gcc-core-3.4.6.tar.gz
         cd gcc-3.4.6
         mkdir build
         cd build
         ./../configure --target=x86_64-elf --host=x86_64-w64-mingw32 --disable-shared --disable-threads --disable-libatomic --disable-libgomp --disable-libmpx --disable-libquadmath --disable-libssp --disable-libvtv --without-isl --without-cloog --disable-multilib --disable-target-libiberty --disable-target-zlib --disable-target-libgdb --disable-plugin --disable-lto --disable-bootstrap --disable-nls --enable-languages=c
         make
      - name: artifact upload
        continue-on-error: true
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/gcc-3.4.3/build
          retention -days: 3
