name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        continue-on-error: true
        run: |
         sudo apt update
         sudo apt install build-essential
         sudo apt install *mingw-w64*
         sudo apt install mingw-w64 m4 *gmp* *mpfr* *mpc* *isl*
         wget https://ftp.gnu.org/gnu/gcc/gcc-4.3.6/gcc-4.3.6.tar.gz
         wget https://ftp.gnu.org/gnu/gmp/gmp-4.1.4.tar.gz
         wget https://ftp.gnu.org/gnu/mpfr/mpfr-2.4.2.tar.gz
         wget https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz
         wget https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.24.tar.bz2
         tar -xf gcc-4.3.6.tar.gz
         cd gcc-4.3.6
         tar -xf ../gmp-4.1.4.tar.bz2
         tar -xf ../mpfr-2.4.2.tar.gz
         tar -xf ../mpc-1.3.1.tar.gz
         tar -xf ../isl-0.24.tar.bz2
         mv gmp-4.1.4 gmp
         mv mpfr-2.4.2 mpfr
         mv mpc-1.3.1 mpc
         mv isl-0.24 isl
         mkdir build
         cd build
         sudo ./../configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --enable-languages=c,c++ --disable-multilib --disable-bootstrap --disable-nls
         sudo make
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/gcc-4.3.6/build/gcc/
          retention -days: 3
