name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        run: |
         sudo apt update
         sudo apt install build-essential
         sudo apt install mingw-w64
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: $HOME/INSTALL/
          retention -days: 3
