name: build
on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: x64
      - name: artifact output
        continue-on-error: true
        run: |
          git config --global core.autocrlf false
          git clone https://github.com/llvm/llvm-project.git
          git checkout llvmorg-17.0.6
          cd llvm-project
          mkdir build
          cd build
          cmake -DLLVM_ENABLE_PROJECTS=clang -G "Visual Studio 16 2019" -A x64 -Thost=x64 ..\llvm
          msbuild clang.vcxproj /t:build /p:configuration=Release /p:platform=x64 -maxcpucount
      - name: artifact upload
        continue-on-error: true
        uses: actions/upload-artifact@v3.0.0
        with:
          name: llvm-clang
          path: .
          retention -days: 3
