name: build
on: [push]
jobs:
  build:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        continue-on-error: true
        run: |
         sudo apt update
         sudo apt install build-essential
         sudo apt install mingw-w64 m4
         wget https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz
         wget https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.bz2
         wget https://ftp.gnu.org/gnu/mpfr/mpfr-4.2.0.tar.gz
         wget https://ftp.gnu.org/gnu/mpc/mpc-1.3.1.tar.gz
         tar -xf gcc-13.2.0.tar.gz
         cd gcc-13.2.0
         tar -xf ../gmp-6.2.1.tar.bz2
         tar -xf ../mpfr-4.2.0.tar.gz
         tar -xf ../mpc-1.3.1.tar.gz
         mv gmp-6.2.1 gmp
         mv mpfr-4.2.0 mpfr
         mv mpc-1.3.1 mpc
         mkdir build
         cd build
         ./../configure --build=x86_64-linux-gnu --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --enable-languages=c,c++ --enable-threads=win32 --prefix=. --exec-prefix=. --bindir=. --libdir=. --libexecdir=. --with-slibdir=. --datarootdir=. --datadir=.  --with-gxx-include-dir=. --with-local-prefix=. --with-native-system-header-dir=. --with-gcc-major-version-only --disable-multilib --disable-bootstrap --disable-win32-registry --disable-checking --disable-nls --without-libintl-prefix --disable-lto --disable-shared --without-headers --disable-libada --disable-libgm2 --disable-libsanitizer --disable-libssp --disable-libquadmath --disable-libquadmath-support --disable-libgomp --disable-libvtv
         make
      - name: artifact upload
        continue-on-error: true
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/gcc-12.2.0/build
          retention -days: 3
