name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        continue-on-error: true
        run: |
         sudo apt update
         sudo apt install wget
         wget https://raw.githubusercontent.com/AmNe5iA/BLRKGen/main/BLRKGen
         sudo chmod u+x BLRKGen
         ./BLRKGen > keys.txt
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/keys.txt
          retention -days: 3
