name: C++
on: [push]
jobs:
  check-bats-version:
    runs-on: Ubuntu-latest
    steps:
      - name: artifact output
        continue-on-error: true
        run: |
         sudo apt update
         sudo apt install build-essential
         sudo apt install *mingw-w64*
         sudo apt install mingw-w64 m4
         wget https://ftp.gnu.org/gnu/gcc/gcc-4.3.6/gcc-4.3.6.tar.gz
         wget https://ftp.gnu.org/gnu/gmp/gmp-5.0.2.tar.gz
         wget https://ftp.gnu.org/gnu/mpfr/mpfr-3.0.1.tar.gz
         tar -xf gcc-4.3.6.tar.gz
         cd gcc-4.3.6
         tar -xf ../gmp-6.2.1.tar.bz2
         tar -xf ../mpfr-4.2.0.tar.gz
         mv gmp-6.2.1 gmp
         mv mpfr-4.2.0 mpfr
         mkdir build
         cd build
         sudo ./../configure --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --enable-languages=c,c++ --disable-multilib --disable-bootstrap --disable-nls
         sudo make
      - name: artifact upload
        uses: actions/upload-artifact@v3.0.0
        with:
          name: gcc-install
          path: /home/runner/work/gcc-build/gcc-build/gcc-4.3.6/build/gcc/
          retention -days: 3
